name: Run Checks on PRs

on:
  pull_request:
    branches:
      - main
permissions:
  contents: read

env:
  PUBLIC_AUTH_CODE: ${{ secrets.PUBLIC_AUTH_CODE }}
  DB_URL: ${{ secrets.DB_URL }}

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install Deps
        run: npm ci
      - name: Svelte Check
        run: npm run check:ci
      - name: Lint Check
        if: (${{ success() }} || ${{ failure() }})
        run: npm run lint
